const fs = require('fs');

function walkDir(dir) {
    fs.readdirSync(dir).forEach(f => {
        let dirPath = dir + '/' + f;
        let isDirectory = fs.statSync(dirPath).isDirectory();
        if (isDirectory && !dirPath.includes('node_modules') && !dirPath.includes('.next')) {
            walkDir(dirPath);
        } else if (dirPath.endsWith('.tsx') || dirPath.endsWith('.ts')) {
            let content = fs.readFileSync(dirPath, 'utf8');
            let original = content;

            // Remove the backslash before the dollar sign generated by my previous script
            if (content.includes('\\${process.env')) {
                content = content.replace(/\\\$\{process\.env/g, '${process.env');
            }

            if (content !== original) {
                fs.writeFileSync(dirPath, content);
                console.log('Fixed', dirPath);
            }
        }
    });
}
walkDir('./app');
walkDir('./src');
